In [40]:
import pandas as pd
import numpy as np
from sklearn import linear_model


In [41]:
df = pd.read_csv('../samples/model1.csv')
df

draught  speed  beaufort  consumption     imo
0         5.0    4.0       8.0     6.506176  234567
1         5.0    4.5       8.0     7.426241  234567
2         5.0    5.0       8.0     8.455103  234567
3         5.0    5.5       7.0     6.494880  234567
4         5.0    5.5       8.0     9.595919  234567
...       ...    ...       ...          ...     ...
1333     13.0   13.5       1.0    43.695985  234567
1334     13.0   13.5       2.0    44.290677  234567
1335     13.0   13.5       3.0    45.203155  234567
1336     13.0   13.5       4.0    46.508317  234567
1337     13.0   13.5       5.0    48.337377  234567

[1338 rows x 5 columns]

In [42]:
df.describe(include='all')

draught        speed     beaufort  consumption       imo
count  1338.000000  1338.000000  1338.000000  1338.000000    1338.0
mean      8.708520    10.866218     4.149477    21.055202  234567.0
std       2.569647     2.715582     2.592796    12.104107       0.0
min       5.000000     4.000000     0.000000     5.779991  234567.0
25%       6.000000     9.000000     2.000000    10.680719  234567.0
50%       9.000000    11.000000     4.000000    18.115707  234567.0
75%      11.000000    13.000000     6.000000    29.545663  234567.0
max      13.000000    17.000000     8.000000    50.610738  234567.0

In [43]:
reg = linear_model.LinearRegression()
reg.fit(df[['draught','speed','beaufort']],df.consumption)
print(reg.coef_,reg.intercept_)


[0.79774899 4.56814297 1.70585612] -42.60886026188495


In [44]:
X = df[['draught','speed','beaufort']]
y = df['consumption']

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.005) 

In [46]:
y_test


493     38.488230
225     13.480767
583     19.107133
921     29.610049
958     11.133538
1292    20.239291
292     22.673987
Name: consumption, dtype: float64

In [47]:
clf = linear_model.LinearRegression()
clf.fit(X_train, y_train)

LinearRegression()

In [48]:
clf.predict(X_test)


array([35.49575472, 15.8187951 , 24.26714659, 31.58677256,  9.51434049,
       23.13601466, 25.56076721])

In [49]:
y_test

493     38.488230
225     13.480767
583     19.107133
921     29.610049
958     11.133538
1292    20.239291
292     22.673987
Name: consumption, dtype: float64

In [50]:
# Model accuracy
clf.score(X_test, y_test)

0.8791970666473722

In [51]:
print(clf.coef_)
clf.intercept_

[0.79768868 4.56864941 1.70652511]


-42.60865707951619