In [21]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [22]:
df = pd.read_csv('../samples/model2.csv')
df

draught  speed  beaufort  added_resistance  consumption      imo
0           8.0    7.0       0.0                 0    16.768106   123456
1           8.0    7.0       0.0                 5    16.987781   123456
2           8.0    7.0       0.0                10    17.207157   123456
3           8.0    7.0       0.0                15    17.426236   123456
4           8.0    7.0       0.0                20    17.645017   123456
...         ...    ...       ...               ...          ...      ...
241299     17.8   14.7       2.0                 0    57.072636  9682978
241300     17.8   14.8       0.0                 0    57.263018  9682978
241301     17.8   14.8       1.0                 0    57.493959  9682978
241302     17.8   14.8       2.0                 0    58.148822  9682978
241303     17.8   14.9       0.0                 0    58.329420  9682978

[241304 rows x 6 columns]

In [55]:
imo = pd.unique(df['imo'])
df1 = df[ df['imo'] == imo[0]]
df2 = df[ df['imo'] == imo[1]]

In [56]:
df1.describe(include='all')

draught         speed      beaufort  added_resistance   consumption  \
count  10000.0  10000.000000  10000.000000      10000.000000  10000.000000   
mean       8.0      9.421710      2.935600         69.100500     32.439761   
std        0.0      1.434861      1.983947         41.675677      8.677315   
min        8.0      7.000000      0.000000          0.000000     16.768106   
25%        8.0      8.200000      1.000000         35.000000     26.110154   
50%        8.0      9.400000      3.000000         70.000000     30.700620   
75%        8.0     10.600000      5.000000        105.000000     37.472797   
max        8.0     12.000000      6.000000        140.000000     58.470754   

            imo  
count   10000.0  
mean   123456.0  
std         0.0  
min    123456.0  
25%    123456.0  
50%    123456.0  
75%    123456.0  
max    123456.0

In [41]:
reg = linear_model.LinearRegression()
reg.fit(df1[['draught','speed','beaufort']],df1.consumption)
print(reg.coef_,reg.intercept_)

[0.         4.52283812 1.80375179] -15.468202032153144


In [40]:
reg2 = linear_model.LinearRegression()
reg2.fit(df2[['draught','speed','beaufort']],df2.consumption)
print(reg2.coef_,reg2.intercept_)

[0.4063522  4.57511598 1.56973988] -18.570543879610995


In [44]:
X = df1[['draught','speed','beaufort']]
y = df1['consumption']

In [50]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.0005) 

In [51]:
y_test

5705    32.304624
818     19.160985
7181    35.468873
1190    30.090063
7039    40.151368
Name: consumption, dtype: float64

In [52]:
clf = linear_model.LinearRegression()
clf.fit(X_train, y_train)

LinearRegression()

In [53]:
# Model accuracy
clf.score(X_test, y_test)

0.9355782711348914

In [54]:
print(clf.coef_)
clf.intercept_

[0.         4.52292442 1.80399462]


-15.470391433671104